// EdenRise multimedia brain — photos, files, audio and a notes/updates timeline on ANY item of the map
// (team-drawn features and the core layers alike), plus a photo layer and "photo here" placement. Uses the Worker (KV + D1).
(function(){
const API="https://edenrise-brain.edenrise.workers.dev";
const L_=(typeof LANG!=="undefined")?LANG:"pt"; const EN=L_==="en";
const T=EN?{taskBtn:"Task",clearBtn:"Register clearing",clearWho:"Cleared by (name):",clearWhen:"Date (YYYY-MM-DD):",clearNote:"Note (machine, hours…):",clearDone:"Clearing recorded — add before/after photos",photo:"Photo",file:"File",audio:"Voice note",note:"Note",add:"Add",send:"Send",notes:"Notes & updates",media:"Photos & files",hist:"History",none:"Nothing yet — add the first photo or note",signin:"Sign in with a team key to add photos and notes",up:"Uploading…",done:"Saved",fail:"Could not upload — try again",del:"Remove",rec:"Recording… tap to stop",cap:"Caption (optional)",photoHere:"Photo here",photoHint:"Tap where the photo belongs, then take or choose it",by:"by",big:"File too big (max 20 MB)",photoPin:"Photo on the map",update:"Update",status:"Status",question:"Question",kinds:{nota:"Note",atualizacao:"Update",pergunta:"Question",decisao:"Decision",limpeza:"Clearing"}}
:{taskBtn:"Tarefa",clearBtn:"Registar limpeza",clearWho:"Limpo por (nome):",clearWhen:"Data (AAAA-MM-DD):",clearNote:"Nota (máquina, horas…):",clearDone:"Limpeza registada — junte fotos antes/depois",photo:"Foto",file:"Ficheiro",audio:"Nota de voz",note:"Nota",add:"Adicionar",send:"Enviar",notes:"Notas e atualizações",media:"Fotos e ficheiros",hist:"Histórico",none:"Ainda nada — adicione a primeira foto ou nota",signin:"Entre com a chave da equipa para adicionar fotos e notas",up:"A enviar…",done:"Guardado",fail:"Não foi possível enviar — tente outra vez",del:"Remover",rec:"A gravar… toque para parar",cap:"Legenda (opcional)",photoHere:"Foto aqui",photoHint:"Toque onde a foto pertence, depois tire-a ou escolha-a",by:"por",big:"Ficheiro demasiado grande (máx. 20 MB)",photoPin:"Foto no mapa",update:"Atualização",status:"Estado",question:"Pergunta",kinds:{nota:"Nota",atualizacao:"Atualização",pergunta:"Pergunta",decisao:"Decisão",limpeza:"Limpeza"}};
const auth=()=>window.edrAuth||{key:"",role:"viewer",actor:""};
const hdr=(ct)=>({...(ct?{"Content-Type":ct}:{}),...(auth().key?{"X-Role-Key":auth().key}:{})});
const when=s=>String(s||"").slice(0,16).replace("T"," ");
const css=document.createElement("style"); css.textContent=`
.mb{margin-top:12px;border-top:1px solid var(--line);padding-top:10px;display:flex;flex-direction:column;gap:10px;font:13px var(--ui)}
.mb .t{font:600 10px var(--mono);letter-spacing:.12em;text-transform:uppercase;color:var(--straw);display:flex;justify-content:space-between;align-items:center}
.mb .acts{display:flex;gap:6px;flex-wrap:wrap} .mb .acts button{display:inline-flex;align-items:center;gap:6px;padding:8px 11px;border-radius:9px;border:1px solid var(--line-2);background:var(--night-2);color:var(--linen);font:600 12px var(--ui);cursor:pointer} .mb .acts button:hover{border-color:var(--straw)} .mb .acts button.rec{background:var(--ember);color:#fff;border-color:var(--ember)}
.mb .gal{display:grid;grid-template-columns:repeat(auto-fill,minmax(78px,1fr));gap:5px} .mb .gal .th{position:relative;aspect-ratio:1;border-radius:8px;overflow:hidden;background:var(--bark);cursor:pointer;border:1px solid var(--line)} .mb .gal .th img{width:100%;height:100%;object-fit:cover;display:block} .mb .gal .th .k{position:absolute;left:0;right:0;bottom:0;padding:3px 5px;font:600 9.5px var(--mono);background:rgba(28,24,19,.75);color:var(--linen);white-space:nowrap;overflow:hidden;text-overflow:ellipsis} .mb .gal .th.f{display:flex;align-items:center;justify-content:center;font-size:24px}
.mb .tl{display:flex;flex-direction:column;gap:6px} .mb .tl .n{padding:8px 10px;border-radius:9px;background:var(--bark);border:1px solid var(--line);position:relative} .mb .tl .n .m{font:500 10.5px var(--mono);color:var(--muted);margin-bottom:3px;display:flex;gap:8px;align-items:center} .mb .tl .n .m i{font-style:normal;font-weight:700;color:var(--linen-2)} .mb .tl .n .m .kd{padding:1px 6px;border-radius:999px;background:var(--night-2);color:var(--straw);font-size:9.5px;letter-spacing:.06em;text-transform:uppercase} .mb .tl .n p{margin:0;white-space:pre-wrap;line-height:1.4} .mb .tl .n.ev{opacity:.75;font-size:12px} .mb .tl .n .x{position:absolute;right:6px;top:6px;border:0;background:transparent;color:var(--muted);cursor:pointer}
.mb .nf{display:flex;flex-direction:column;gap:6px} .mb .nf textarea{min-height:64px;padding:9px 10px;background:var(--bark);color:var(--linen);border:1px solid var(--line-2);border-radius:9px;font:13.5px var(--ui);resize:vertical} .mb .nf .row{display:flex;gap:6px;align-items:center} .mb .nf select{padding:7px 8px;background:var(--bark);color:var(--linen);border:1px solid var(--line-2);border-radius:8px;font:12px var(--ui)} .mb .nf button{margin-left:auto;padding:8px 14px;border-radius:9px;border:0;background:var(--oak);color:var(--bark);font:700 12.5px var(--ui);cursor:pointer}
.mb .empty{color:var(--muted);font-size:12.5px} .mb .prog{height:3px;background:var(--line);border-radius:2px;overflow:hidden} .mb .prog i{display:block;height:100%;background:var(--straw);width:0;transition:width .2s}
#lightbox{position:fixed;inset:0;z-index:5000;background:rgba(12,10,8,.94);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;padding:16px} #lightbox[hidden]{display:none} #lightbox img,#lightbox video{max-width:min(96vw,1400px);max-height:78vh;border-radius:10px;box-shadow:0 10px 40px rgba(0,0,0,.6)} #lightbox .cap{color:var(--linen);font:14px var(--ui);text-align:center;max-width:800px} #lightbox .meta{color:var(--muted);font:11.5px var(--mono)} #lightbox .bar{display:flex;gap:8px} #lightbox .bar button,#lightbox .bar a{padding:8px 14px;border-radius:999px;border:1px solid var(--line-2);background:var(--night-2);color:var(--linen);font:600 12px var(--ui);cursor:pointer;text-decoration:none} #lightbox .bar .x{border-color:var(--ember);color:var(--ember)}
.ph-pin{width:34px;height:34px;border-radius:50%;border:2px solid var(--straw);overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.6);background:var(--bark)} .ph-pin img{width:100%;height:100%;object-fit:cover}
@media(pointer:coarse){ .mb .acts button{padding:11px 13px;font-size:13px} }`;
document.head.appendChild(css);
/* ---------- lightbox ---------- */
const lb=document.createElement("div"); lb.id="lightbox"; lb.hidden=true; document.body.appendChild(lb); lb.onclick=e=>{ if(e.target===lb) lb.hidden=true; };
function openLightbox(items,i,onDelete){ const show=()=>{ const m=items[i]; const src=`${API}/media/${m.id}`; const canDel=auth().role==="leader"||(auth().role!=="viewer"&&m.by===auth().actor);
  lb.innerHTML=`${m.kind==="video"?`<video src="${src}" controls autoplay playsinline></video>`:m.kind==="audio"?`<audio src="${src}" controls autoplay style="width:min(90vw,600px)"></audio>`:m.kind==="foto"?`<img src="${src}" alt="">`:`<div style="font-size:64px">📄</div>`}<div class="cap">${m.caption||""}</div><div class="meta">${m.by||"—"} · ${when(m.at)} · ${m.mime||""} · ${Math.round((m.size||0)/1024)} KB${m.lat?` · ${(+m.lat).toFixed(5)}, ${(+m.lon).toFixed(5)}`:""}</div><div class="bar">${items.length>1?`<button id="lbp">‹</button><span style="color:var(--muted);font:12px var(--mono);align-self:center">${i+1}/${items.length}</span><button id="lbn">›</button>`:""}<a href="${src}" target="_blank" download>⤓</a>${canDel?`<button class="x" id="lbd">${T.del}</button>`:""}<button id="lbx">✕</button></div>`;
  lb.hidden=false; const q=s=>lb.querySelector(s); if(q("#lbp")) q("#lbp").onclick=()=>{ i=(i-1+items.length)%items.length; show(); }; if(q("#lbn")) q("#lbn").onclick=()=>{ i=(i+1)%items.length; show(); }; q("#lbx").onclick=()=>lb.hidden=true;
  if(q("#lbd")) q("#lbd").onclick=async()=>{ if(!confirm(T.del+"?")) return; await fetch(`${API}/media/${m.id}?actor=${encodeURIComponent(auth().actor)}`,{method:"DELETE",headers:hdr()}); lb.hidden=true; onDelete&&onDelete(); }; }; show(); }
/* ---------- helpers: image compression, upload, recording ---------- */
function shrink(file,max=1600,q=.82){ return new Promise(res=>{ if(!file.type.startsWith("image/")||file.type==="image/gif") return res({blob:file,w:null,h:null}); const img=new Image(); const u=URL.createObjectURL(file); img.onload=()=>{ const s=Math.min(1,max/Math.max(img.width,img.height)); const c=document.createElement("canvas"); c.width=Math.round(img.width*s); c.height=Math.round(img.height*s); c.getContext("2d").drawImage(img,0,0,c.width,c.height); c.toBlob(b=>{ URL.revokeObjectURL(u); res({blob:b||file,w:c.width,h:c.height}); },"image/jpeg",q); }; img.onerror=()=>res({blob:file,w:null,h:null}); img.src=u; }); }
function upload(blob,params,onProg){ return new Promise((res,rej)=>{ const x=new XMLHttpRequest(); const qs=Object.entries(params).filter(([k,v])=>v!=null&&v!=="").map(([k,v])=>`${k}=${encodeURIComponent(v)}`).join("&"); x.open("POST",`${API}/media?${qs}`); x.setRequestHeader("Content-Type",blob.type||"application/octet-stream"); if(auth().key) x.setRequestHeader("X-Role-Key",auth().key); x.upload.onprogress=e=>{ if(e.lengthComputable&&onProg) onProg(e.loaded/e.total); }; x.onload=()=>{ try{ const d=JSON.parse(x.responseText); d.ok?res(d):rej(d); }catch(e){ rej({error:"parse"}); } }; x.onerror=()=>rej({error:"net"}); x.send(blob); }); }
async function pickAndUpload(kind,fid,ll,box,refresh){ if(auth().role==="viewer"){ toast&&toast(T.signin); return; } const inp=document.createElement("input"); inp.type="file"; if(kind==="foto"){ inp.accept="image/*"; inp.setAttribute("capture","environment"); } inp.multiple=kind!=="foto";
  inp.onchange=async()=>{ const files=[...inp.files]; if(!files.length) return; const prog=document.createElement("div"); prog.className="prog"; prog.innerHTML="<i></i>"; box.prepend(prog); let n=0;
    for(const f of files){ if(f.size>20*1024*1024){ toast&&toast(T.big); continue; } const cap=files.length===1?(prompt(T.cap,"")||""):""; const {blob,w,h}=await shrink(f); try{ await upload(blob,{feature_id:fid,lat:ll?ll.lat:null,lon:ll?ll.lng:null,caption:cap,actor:auth().actor,w,h},p=>prog.firstChild.style.width=Math.round(p*100)+"%"); n++; }catch(e){ toast&&toast(T.fail); } }
    prog.remove(); if(n){ toast&&toast(T.done); refresh(); if(window.reloadMediaLayer) reloadMediaLayer(); } }; inp.click(); }
let rec=null;
async function recordVoice(btn,fid,ll,refresh){ if(auth().role==="viewer"){ toast&&toast(T.signin); return; } if(rec){ rec.stop(); return; } try{ const st=await navigator.mediaDevices.getUserMedia({audio:true}); const mime=MediaRecorder.isTypeSupported("audio/mp4")?"audio/mp4":MediaRecorder.isTypeSupported("audio/webm")?"audio/webm":""; rec=new MediaRecorder(st,mime?{mimeType:mime}:{}); const chunks=[]; rec.ondataavailable=e=>chunks.push(e.data); btn.classList.add("rec"); btn.textContent="■ "+T.rec;
  rec.onstop=async()=>{ st.getTracks().forEach(t=>t.stop()); btn.classList.remove("rec"); btn.textContent="🎤 "+T.audio; const blob=new Blob(chunks,{type:rec.mimeType||"audio/webm"}); rec=null; const cap=prompt(T.cap,"")||""; try{ await upload(blob,{feature_id:fid,lat:ll?ll.lat:null,lon:ll?ll.lng:null,caption:cap,actor:auth().actor}); toast&&toast(T.done); refresh(); }catch(e){ toast&&toast(T.fail); } }; rec.start(); }catch(e){ toast&&toast(EN?"Microphone not available":"Microfone indisponível"); } }
/* ---------- the item brain block (gallery + timeline + add) ---------- */
window.edrItem=async function(fid,container,opts){ opts=opts||{}; const ll=opts.latlng||null; const box=document.createElement("div"); box.className="mb"; container.appendChild(box);
  const render=async()=>{ let d={media:[],notes:[],history:[],events:[]}; try{ d=await fetch(`${API}/item/${encodeURIComponent(fid)}`).then(r=>r.json()); }catch(e){}
    const a=auth(); const can=a.role!=="viewer"; const media=d.media||[], notes=d.notes||[];
    const ev=(d.events||[]).filter(e=>!/^(media|note)\./.test(e.action)).map(e=>({at:e.at,by:e.actor,kind:"ev",text:`${e.action.replace("feature.","")}${e.payload&&e.payload.status?" → "+e.payload.status:""}${e.payload&&e.payload.note?" · "+e.payload.note:""}`}));
    const tl=[...notes.map(n=>({...n,kind:n.kind||"nota"})),...ev].sort((x,y)=>String(y.at).localeCompare(String(x.at)));
    box.innerHTML=`<div class="t"><span>${T.media} · ${media.length}</span></div>
      <div class="acts">${can?`<button id="mbp">📷 ${T.photo}</button><button id="mbf">📎 ${T.file}</button><button id="mba">🎤 ${T.audio}</button>${window.edrTasks&&!fid.startsWith("task:")?`<button id="mbt2">✔ ${T.taskBtn}</button>`:""}${fid.startsWith("fire_fuel_strips:")?`<button id="mbc" style="border-color:var(--ember)">🔥 ${T.clearBtn}</button>`:""}`:`<span class="empty">${T.signin}</span>`}</div>
      ${media.length?`<div class="gal">${media.map((m,i)=>`<div class="th ${m.kind==="foto"?"":"f"}" data-i="${i}" title="${m.caption||""}">${m.kind==="foto"?`<img loading="lazy" src="${API}/media/${m.id}" alt="">`:m.kind==="video"?"🎬":m.kind==="audio"?"🎤":"📄"}<span class="k">${m.caption||m.by||""}</span></div>`).join("")}</div>`:""}
      <div class="t"><span>${T.notes} · ${notes.length}</span></div>
      ${can?`<div class="nf"><textarea id="mbt" placeholder="${T.note}…"></textarea><div class="row"><select id="mbk">${Object.entries(T.kinds).map(([k,v])=>`<option value="${k}">${v}</option>`).join("")}</select><button id="mbs">${T.send}</button></div></div>`:""}
      ${tl.length?`<div class="tl">${tl.map(n=>`<div class="n ${n.kind==="ev"?"ev":""}">${n.kind!=="ev"&&(a.role==="leader"||(can&&n.by===a.actor))?`<button class="x" data-n="${n.id}" title="${T.del}">✕</button>`:""}<div class="m"><i>${n.by||"—"}</i><span>${when(n.at)}</span>${n.kind!=="ev"?`<span class="kd">${T.kinds[n.kind]||n.kind}</span>`:""}</div><p>${(n.text||"").replace(/</g,"&lt;")}</p></div>`).join("")}</div>`:(media.length?"":`<div class="empty">${T.none}</div>`)}`;
    const q=s=>box.querySelector(s);
    if(q("#mbp")) q("#mbp").onclick=()=>pickAndUpload("foto",fid,ll,box,render);
    if(q("#mbt2")) q("#mbt2").onclick=()=>window.edrTasks.newTask({feature_id:fid,latlng:ll,title:""});
    if(q("#mbc")) q("#mbc").onclick=async()=>{ const who=prompt(T.clearWho,a.actor||""); if(who===null) return; const when=prompt(T.clearWhen,new Date().toISOString().slice(0,10)); if(!when) return; const note=prompt(T.clearNote,"")||""; const text=`${EN?"Cleared":"Limpeza"} ${when} · ${who}${note?" · "+note:""}`; const r=await fetch(`${API}/item/${encodeURIComponent(fid)}/notes`,{method:"POST",headers:hdr("application/json"),body:JSON.stringify({text,kind:"limpeza",actor:a.actor||who,lat:ll?ll.lat:null,lon:ll?ll.lng:null})}).then(r=>r.json()).catch(()=>({})); if(r.ok){ toast&&toast(T.clearDone); render(); } else toast&&toast(T.fail); }; if(q("#mbf")) q("#mbf").onclick=()=>pickAndUpload("file",fid,ll,box,render); if(q("#mba")) q("#mba").onclick=e=>recordVoice(e.currentTarget,fid,ll,render);
    box.querySelectorAll(".gal .th").forEach(t=>t.onclick=()=>openLightbox(media,+t.dataset.i,render));
    if(q("#mbs")) q("#mbs").onclick=async()=>{ const text=q("#mbt").value.trim(); if(!text) return; const r=await fetch(`${API}/item/${encodeURIComponent(fid)}/notes`,{method:"POST",headers:hdr("application/json"),body:JSON.stringify({text,kind:q("#mbk").value,actor:a.actor,lat:ll?ll.lat:null,lon:ll?ll.lng:null})}).then(r=>r.json()).catch(()=>({})); if(r.ok){ toast&&toast(T.done); render(); } else toast&&toast(T.fail); };
    box.querySelectorAll(".tl .x").forEach(b=>b.onclick=async()=>{ if(!confirm(T.del+"?")) return; await fetch(`${API}/notes/${b.dataset.n}?actor=${encodeURIComponent(a.actor)}`,{method:"DELETE",headers:hdr()}); render(); }); };
  render(); return box; };
/* ---------- photo layer: every geotagged photo as a round thumbnail on the map ---------- */
const photoLayer=L.layerGroup(); let photoItems=[];
window.reloadMediaLayer=async function(){ try{ const d=await fetch(API+"/media").then(r=>r.json()); photoItems=d.media||[]; photoLayer.clearLayers(); for(const m of photoItems){ if(m.kind!=="foto") continue; const mk=L.marker([m.lat,m.lon],{icon:L.divIcon({className:"",html:`<div class="ph-pin"><img src="${API}/media/${m.id}" alt=""></div>`,iconSize:[34,34],iconAnchor:[17,17]}),zIndexOffset:400}); mk.on("click",()=>openLightbox(photoItems.filter(x=>x.kind==="foto"),photoItems.filter(x=>x.kind==="foto").indexOf(m),reloadMediaLayer)); photoLayer.addLayer(mk); } if(photoItems.length&&!map.hasLayer(photoLayer)) photoLayer.addTo(map); }catch(e){} };
reloadMediaLayer();
/* ---------- "photo here": place a photo at a tapped point (or GPS) as its own pin ---------- */
window.edrPhotoHere=function(latlng){ if(auth().role==="viewer"){ toast&&toast(T.signin); return; } const tmp=document.createElement("div"); pickAndUpload("foto",null,latlng,tmp,()=>{}); };
})();
