// Permaculture design layers — contours, aspect/slope highlighters, frost pockets, keypoints & keylines, sun hours, zones & sectors.
// Adds a "🌱 Permacultura & Design" category to the sidebar; data lazily from perma/<layer>.json and perma/sun_*.png.
(function(){
const EN=(typeof LANG!=="undefined")&&LANG==="en";
const T=EN?{cat:"Permaculture & design",c1:"Contours 1 m",c5:"Contours 5 m",aspect:"Aspect",N:"North-facing (cold, damp)",E:"East-facing (morning sun)",S:"South-facing (warm, dry)",W:"West-facing (hot afternoons)",slope:"Slope",s1:"Flat 0–4° (build, ponds, frost)",s2:"Gentle 4–10° (fields, swales)",s3:"Moderate 10–20° (terraces, trees)",s4:"Steep >20° (protect, forest)",frost:"Frost pockets (cold-air pools)",fh:"high",fm:"moderate",key:"Keypoints & keylines",sun:"Sun hours (terrain shadow)",sw:"Winter solstice",se:"Equinox",ss:"Summer solstice",zones:"Zones (from the house)",sect:"Sectors (sun & wind)",centre:"Tap the map to set the zone centre",opacity:"opacity",kpTip:"Keypoint: where the valley changes from steep to gentle — the classic place to start water harvesting (Yeomans)",zoneTip:"Zone 1 daily · zone 2 often · zone 3 weekly · zone 4 rare · zone 5 wild",load:"Loading permaculture layers…"}
:{cat:"Permacultura & design",c1:"Curvas de nível 1 m",c5:"Curvas de nível 5 m",aspect:"Exposição",N:"Virado a norte (frio, húmido)",E:"Virado a leste (sol da manhã)",S:"Virado a sul (quente, seco)",W:"Virado a oeste (tardes quentes)",slope:"Declive",s1:"Plano 0–4° (construir, charcas, geada)",s2:"Suave 4–10° (campos, valas de infiltração)",s3:"Moderado 10–20° (socalcos, árvores)",s4:"Íngreme >20° (proteger, floresta)",frost:"Bolsas de geada (ar frio)",fh:"elevado",fm:"moderado",key:"Keypoints & keylines",sun:"Horas de sol (sombra do terreno)",sw:"Solstício de inverno",se:"Equinócio",ss:"Solstício de verão",zones:"Zonas (a partir da casa)",sect:"Sectores (sol e vento)",centre:"Toque no mapa para definir o centro das zonas",opacity:"opacidade",kpTip:"Keypoint: onde o vale passa de íngreme a suave — o sítio clássico para começar a reter água (Yeomans)",zoneTip:"Zona 1 diário · zona 2 frequente · zona 3 semanal · zona 4 raro · zona 5 selvagem",load:"A carregar camadas de permacultura…"};
const COL={N:"#5b8fb9",E:"#9fb789",S:"#e0a83a",W:"#e07b39",s1:"#7f9a6a",s2:"#c9a227",s3:"#e07b39",s4:"#b3413a",fh:"#8fd3ff",fm:"#c9e8ff",key:"#ff4fd8",c1:"#f1e9d8",c5:"#f1e9d8"};
const layers={}; const grp=L.layerGroup().addTo(map);
const data={}, loading={}; const STAMP=new Date().toISOString().slice(0,10);
function load(name){ if(data[name]) return Promise.resolve(data[name]); if(loading[name]) return loading[name]; if(window.showLoading) showLoading(T.load);
  loading[name]=fetch(`perma/${name}.json?d=${STAMP}`).then(r=>{ if(!r.ok) throw new Error(name); return r.json(); }).then(j=>{ data[name]=j; if(window.showLoading) showLoading(null); return j; }).catch(e=>{ if(window.showLoading) showLoading(null); loading[name]=null; throw e; }); return loading[name]; }
const NEED={c1:"contours_1m",c5:"contours_5m",N:"aspect_classes",E:"aspect_classes",S:"aspect_classes",W:"aspect_classes",s1:"slope_classes",s2:"slope_classes",s3:"slope_classes",s4:"slope_classes",frost:"frost_pockets"};
function mk(key,build){ if(layers[key]) return layers[key]; layers[key]=build(); return layers[key]; }
async function toggle(key,on){ if(!on){ if(layers[key]) grp.removeLayer(layers[key]); return; } try{ if(key==="key") await Promise.all([load("keylines"),load("keypoints")]); else await load(NEED[key]); }catch(e){ toast&&toast("perma/"+(NEED[key]||key)+".json?"); return; }
  const l=mk(key,()=>{
    if(key==="c1"||key==="c5"){ const fc=data[key==="c1"?"contours_1m":"contours_5m"]; return L.geoJSON(fc,{style:f=>({color:"#f1e9d8",weight:f.properties.major?1.4:0.6,opacity:f.properties.major?.9:.55,interactive:false}),onEachFeature:(f,l)=>{ if(f.properties.major) l.bindTooltip(String(f.properties.elev)+" m",{permanent:false,direction:"center",className:"ctip"}); }}); }
    if(["N","E","S","W"].includes(key)) return L.geoJSON(data.aspect_classes,{filter:f=>f.properties.cls===key,style:{color:COL[key],weight:0,fillColor:COL[key],fillOpacity:.38},onEachFeature:(f,l)=>l.bindTooltip(`${T[key]} · ${(f.properties.area_m2/1e4).toFixed(2)} ha`)});
    if(["s1","s2","s3","s4"].includes(key)){ const cls={s1:"0-4",s2:"4-10",s3:"10-20",s4:">20"}[key]; return L.geoJSON(data.slope_classes,{filter:f=>f.properties.cls===cls,style:{color:COL[key],weight:0,fillColor:COL[key],fillOpacity:.38},onEachFeature:(f,l)=>l.bindTooltip(`${T[key]} · ${(f.properties.area_m2/1e4).toFixed(2)} ha`)}); }
    if(key==="frost") return L.geoJSON(data.frost_pockets,{style:f=>({color:"#8fd3ff",weight:1,dashArray:"3 3",fillColor:f.properties.cls==="elevado"?COL.fh:COL.fm,fillOpacity:f.properties.cls==="elevado"?.5:.3}),onEachFeature:(f,l)=>l.bindTooltip(`${T.frost}: ${f.properties.cls==="elevado"?T.fh:T.fm} · ${(f.properties.area_m2/1e4).toFixed(2)} ha`)});
    if(key==="key"){ const g=L.layerGroup(); g.addLayer(L.geoJSON(data.keylines,{style:{color:COL.key,weight:2.5,dashArray:"8 5"},onEachFeature:(f,l)=>l.bindTooltip(`keyline ${f.properties.elev} m`)})); g.addLayer(L.geoJSON(data.keypoints,{pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:7,color:"#fff",weight:2,fillColor:COL.key,fillOpacity:1}),onEachFeature:(f,l)=>l.bindTooltip(`${T.kpTip}<br>${f.properties.elev} m · ${EN?"above":"acima"} ${f.properties.slope_above_pct}% · ${EN?"below":"abaixo"} ${f.properties.slope_below_pct}%`)})); return g; }
    return L.layerGroup(); });
  grp.addLayer(l); }
/* sun overlays */
let sunLayer=null, sunKey=null, sunOpacity=.7, sunBounds=null;
async function sun(key){ if(sunLayer){ map.removeLayer(sunLayer); sunLayer=null; } sunKey=key; if(!key) return; if(!sunBounds){ try{ sunBounds=(await fetch("perma/bounds.json").then(r=>r.json())).bounds; }catch(e){ return; } } sunLayer=L.imageOverlay(`perma/sun_${key}.png`,sunBounds,{opacity:sunOpacity,interactive:false}).addTo(map); }
/* zones & sectors */
let centre=null, zoneLayer=null, sectLayer=null; try{ const c=JSON.parse(localStorage.getItem("edr_zone_centre")||"null"); if(c) centre=L.latLng(c[0],c[1]); }catch(e){}
function findHouse(){ try{ const fc=DATA.buildings_pt; const f=fc.features.find(x=>/casa principal|main house|casa grande|casa m[ãa]e/i.test(x.properties.name||""))||fc.features.find(x=>/\bcasa\b/i.test(x.properties.name||""))||fc.features[0]; const c=(window.turf?turf.centroid(f):null); const xy=c?c.geometry.coordinates:(function flat(a){ return (typeof a[0]==="number")?a:flat(a[0]); })(f.geometry.coordinates); const ll=L.latLng(xy[1],xy[0]); return (ll&&isFinite(ll.lat))?ll:map.getCenter(); }catch(e){ return map.getCenter(); } }
function zones(on){ if(zoneLayer){ map.removeLayer(zoneLayer); zoneLayer=null; } if(!on) return; const c=centre||findHouse(); zoneLayer=L.layerGroup(); const R=[[60,"1"],[150,"2"],[400,"3"],[900,"4"]]; R.forEach(([r,z],i)=>zoneLayer.addLayer(L.circle(c,{radius:r,color:"#f1e9d8",weight:1.2,dashArray:"6 6",fill:false,interactive:false}).bindTooltip(`${EN?"zone":"zona"} ${z} · ${r} m`,{permanent:true,direction:"top",className:"ctip",offset:[0,-r/2]})));
  zoneLayer.addLayer(L.circleMarker(c,{radius:6,color:"#fff",fillColor:"#c9a227",fillOpacity:1}).bindTooltip(T.zoneTip)); zoneLayer.addTo(map); }
function wedge(c,a0,a1,r,opts){ const P=(a)=>{ const t=a*Math.PI/180; const kx=111320*Math.cos(c.lat*Math.PI/180); return L.latLng(c.lat+Math.cos(t)*r/110540,c.lng+Math.sin(t)*r/kx); }; const pts=[c]; for(let a=a0;a<=a1;a+=3) pts.push(P(a)); pts.push(c); return L.polygon(pts,opts); }
function sectors(on){ if(sectLayer){ map.removeLayer(sectLayer); sectLayer=null; } if(!on) return; const c=centre||findHouse(); sectLayer=L.layerGroup(); const R=700;
  sectLayer.addLayer(wedge(c,118,242,R,{color:"#ffd166",weight:1,fillColor:"#ffd166",fillOpacity:.12}).bindTooltip(EN?"Winter sun · sunrise 118° → sunset 242° (21 Dec, lat 37.5°)":"Sol de inverno · nascer 118° → pôr 242° (21 dez, lat 37,5°)"));
  sectLayer.addLayer(wedge(c,60,300,R*1.1,{color:"#ffb703",weight:1,fillColor:"#ffb703",fillOpacity:.07}).bindTooltip(EN?"Summer sun · sunrise 60° → sunset 300° (21 Jun)":"Sol de verão · nascer 60° → pôr 300° (21 jun)"));
  sectLayer.addLayer(wedge(c,300,345,R*.8,{color:"#5bc0de",weight:1,dashArray:"4 4",fillColor:"#5bc0de",fillOpacity:.12}).bindTooltip(EN?"Prevailing wind · NW (Nortada, summer afternoons; Atlantic)":"Vento dominante · NO (nortada, tardes de verão; Atlântico)"));
  sectLayer.addLayer(wedge(c,40,110,R*.8,{color:"#e07b39",weight:1,dashArray:"4 4",fillColor:"#e07b39",fillOpacity:.14}).bindTooltip(EN?"Fire sector · hot dry E/NE winds (levante) drive the worst fire days":"Sector de fogo · ventos quentes e secos de E/NE (levante) nos piores dias"));
  sectLayer.addTo(map); }
function pickCentre(){ toast&&toast(T.centre); map.getContainer().style.cursor="crosshair"; map.once("click",e=>{ centre=e.latlng; try{ localStorage.setItem("edr_zone_centre",JSON.stringify([centre.lat,centre.lng])); }catch(err){} map.getContainer().style.cursor=""; if(zoneLayer) zones(true); if(sectLayer) sectors(true); }); }
/* sidebar category */
const css=document.createElement("style"); css.textContent=`.ctip{background:rgba(28,24,19,.85);color:var(--linen);border:0;font:600 10.5px var(--mono);padding:2px 6px;box-shadow:none} .ctip::before{display:none} .pm-sub{font:600 10px var(--mono);letter-spacing:.1em;text-transform:uppercase;color:var(--muted);margin:8px 0 2px 6px}`; document.head.appendChild(css);
function render(){ const tree=document.getElementById("tree"); if(!tree||document.getElementById("permacat")) return; const cat=document.createElement("div"); cat.id="permacat"; cat.className="cat";
  const row=(id,label,color)=>`<label class="lyr" data-k="${id}"><span class="sw" style="display:inline-block;width:10px;height:10px;border-radius:3px;background:${color}"></span><span class="nm">${label}</span><span class="tg"><input type="checkbox"><i></i></span></label>`;
  cat.innerHTML=`<div class="ch"><svg class="chev" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m9 6 6 6-6 6"/></svg><span class="ico">🌱</span><span class="cn">${T.cat}</span><span class="cc">0</span><span class="tg"><input type="checkbox" class="gc"><i></i></span></div><div class="cb">
    ${row("c5",T.c5,COL.c5)}${row("c1",T.c1,COL.c1)}<div class="pm-sub">${T.aspect}</div>${["N","E","S","W"].map(k=>row(k,T[k],COL[k])).join("")}<div class="pm-sub">${T.slope}</div>${["s1","s2","s3","s4"].map(k=>row(k,T[k],COL[k])).join("")}<div class="pm-sub">${EN?"Climate":"Clima"}</div>${row("frost",T.frost,COL.fh)}
    <div class="pm-sub">${T.sun}</div><div class="lyr" style="gap:5px;flex-wrap:wrap"><button data-sun="winter" class="sunb">${T.sw}</button><button data-sun="equinox" class="sunb">${T.se}</button><button data-sun="summer" class="sunb">${T.ss}</button><button data-sun="" class="sunb">✕</button><input type="range" id="sunop" min=".2" max="1" step=".05" value=".7" title="${T.opacity}" style="width:70px"></div>
    <div class="pm-sub">${EN?"Water":"Água"}</div>${row("key",T.key,COL.key)}
    <div class="pm-sub">${EN?"Design":"Design"}</div>${row("zones",T.zones,"#f1e9d8")}${row("sect",T.sect,"#ffd166")}<div class="lyr"><button id="pmcentre" style="font:600 11px var(--ui);padding:5px 10px;border-radius:999px;border:1px solid var(--line-2);background:transparent;color:var(--linen);cursor:pointer">📍 ${EN?"Set centre":"Definir centro"}</button></div></div>`;
  cat.querySelector(".ch").onclick=e=>{ if(e.target.closest(".tg")) return; cat.classList.toggle("open"); };
  const cc=cat.querySelector(".cc"); const refresh=()=>{ const n=[...cat.querySelectorAll('label.lyr input[type=checkbox]')].filter(i=>i.checked).length; cc.textContent=n; cc.classList.toggle("on",n>0); };
  cat.querySelectorAll("label.lyr").forEach(l=>{ const k=l.dataset.k; l.querySelector("input").onchange=async e=>{ if(k==="zones") zones(e.target.checked); else if(k==="sect") sectors(e.target.checked); else await toggle(k,e.target.checked); refresh(); }; });
  cat.querySelector(".gc").onchange=e=>{ cat.querySelectorAll("label.lyr input").forEach(i=>{ if(i.checked!==e.target.checked){ i.checked=e.target.checked; i.dispatchEvent(new Event("change")); } }); };
  cat.querySelectorAll(".sunb").forEach(b=>b.onclick=()=>{ cat.querySelectorAll(".sunb").forEach(x=>x.style.background=""); if(b.dataset.sun) b.style.background="var(--straw)"; sun(b.dataset.sun||null); }); cat.querySelector("#sunop").oninput=e=>{ sunOpacity=+e.target.value; if(sunLayer) sunLayer.setOpacity(sunOpacity); };
  cat.querySelector("#pmcentre").onclick=pickCentre;
  const style=document.createElement("style"); style.textContent=`#permacat .sunb{font:600 11px var(--ui);padding:5px 9px;border-radius:999px;border:1px solid var(--line-2);background:transparent;color:var(--linen);cursor:pointer}`; document.head.appendChild(style);
  const team=document.getElementById("teamcat"); if(team&&team.nextSibling) tree.insertBefore(cat,team.nextSibling); else { const first=tree.querySelector(".cat"); if(first) tree.insertBefore(cat,first.nextSibling||first); else tree.appendChild(cat); } }
(function wait(n){ if(document.getElementById("tree")&&document.querySelector("#tree .cat")) render(); else if(n<60) setTimeout(()=>wait(n+1),250); })(0);
window.edrPerma={toggle,sun,zones,sectors};
})();
