// Presence — who is on the map right now (signed-in users only), where they are looking, as small initials on the map and a counter in the top bar.
(function(){
const API="https://edenrise-brain.edenrise.workers.dev"; const EN=(typeof LANG!=="undefined")&&LANG==="en";
const auth=()=>window.edrAuth||{key:"",role:"viewer",actor:""};
const css=document.createElement("style"); css.textContent=`#appnav .pres{display:inline-flex;align-items:center;gap:6px;margin-right:8px;color:var(--linen-2);font:600 11px var(--mono);letter-spacing:.06em;cursor:default} #appnav .pres i{width:8px;height:8px;border-radius:50%;background:var(--oak);display:inline-block;box-shadow:0 0 0 3px rgba(127,154,106,.25)} .pr-pin{width:26px;height:26px;border-radius:50%;background:var(--water);color:#fff;border:2px solid #fff;display:flex;align-items:center;justify-content:center;font:800 10px var(--ui);box-shadow:0 2px 8px rgba(0,0,0,.5)}`; document.head.appendChild(css);
const layer=L.layerGroup().addTo(map); let el=null;
(function mk(n){ const edit=document.getElementById("nav-edit"); if(!edit){ if((n||0)<40) setTimeout(()=>mk((n||0)+1),150); return; } el=document.createElement("span"); el.className="pres"; el.hidden=true; el.innerHTML=`<i></i><span class="n">0</span>`; edit.parentNode.insertBefore(el,edit); })(0);
async function beat(){ const a=auth(); if(!a.actor||document.hidden) return; const c=map.getCenter(); try{ const d=await fetch(API+"/presence",{method:"POST",headers:{"Content-Type":"application/json",...(a.key?{"X-Role-Key":a.key}:{})},body:JSON.stringify({actor:a.actor,lat:+c.lat.toFixed(5),lon:+c.lng.toFixed(5),zoom:+map.getZoom().toFixed(1),page:"map"})}).then(r=>r.json()); show(d.others||[]); }catch(e){} }
function show(others){ layer.clearLayers(); if(el){ el.hidden=!others.length; el.querySelector(".n").textContent=others.length; el.title=others.map(o=>`${o.actor} · ${String(o.at).slice(11,16)}`).join("\n"); }
  for(const o of others){ if(o.lat==null) continue; const ini=String(o.actor).split(/\s+/).map(w=>w[0]).join("").slice(0,2).toUpperCase(); const m=L.marker([o.lat,o.lon],{icon:L.divIcon({className:"",html:`<div class="pr-pin" title="${o.actor}">${ini}</div>`,iconSize:[26,26],iconAnchor:[13,13]}),interactive:true,zIndexOffset:900}); m.bindTooltip(`${o.actor} · ${EN?"looking here":"a ver aqui"} · ${String(o.at).slice(11,16)}`); layer.addLayer(m); } }
setInterval(beat,30000); setTimeout(beat,4000); document.addEventListener("visibilitychange",()=>{ if(!document.hidden) beat(); });
})();
