// Sensors — live readings from any device that can POST (LoRaWAN gateway, ESP32, a phone script): tank levels, soil moisture, gate state…
// Shows each sensor as a pin with its latest value, a 7-day sparkline on tap, alert colours, and (leadership) a register form.
(function(){
const API="https://edenrise-brain.edenrise.workers.dev"; const EN=(typeof LANG!=="undefined")&&LANG==="en";
const auth=()=>window.edrAuth||{key:"",role:"viewer",actor:""}; const hdr=()=>({"Content-Type":"application/json",...(auth().key?{"X-Role-Key":auth().key}:{})});
const T=EN?{title:"Sensors",none:"No sensors yet. A device posts readings to the Worker; leadership registers it here.",reg:"Register sensor",id:"Sensor id (as the device sends it)",name:"Name",kind:"Kind (tank, soil, gate, weather…)",unit:"Unit (%, m³, cm, °C)",min:"Alert below",max:"Alert above",place:"Tap the map where it is",save:"Save",how:"How a device posts",last:"last",ago:"ago",alert:"ALERT",noread:"no readings yet"}
:{title:"Sensores",none:"Ainda sem sensores. Um aparelho envia leituras para o Worker; a liderança regista-o aqui.",reg:"Registar sensor",id:"Id do sensor (como o aparelho envia)",name:"Nome",kind:"Tipo (tanque, solo, portão, meteo…)",unit:"Unidade (%, m³, cm, °C)",min:"Alerta abaixo de",max:"Alerta acima de",place:"Toque no mapa onde está",save:"Guardar",how:"Como um aparelho envia",last:"última",ago:"atrás",alert:"ALERTA",noread:"ainda sem leituras"};
const css=document.createElement("style"); css.textContent=`.sn-pin{min-width:34px;height:26px;padding:0 7px;border-radius:13px;background:var(--night-2);color:var(--linen);border:2px solid var(--water);display:flex;align-items:center;justify-content:center;font:700 11px var(--mono);box-shadow:0 2px 8px rgba(0,0,0,.5);white-space:nowrap} .sn-pin.al{border-color:var(--ember);background:var(--ember);color:#fff} .sn-pin.old{opacity:.55}`; document.head.appendChild(css);
const layer=L.layerGroup(); let sensors=[];
function ago(at){ const m=Math.round((Date.now()-new Date(at))/60000); return m<60?`${m} min`:m<1440?`${Math.round(m/60)} h`:`${Math.round(m/1440)} d`; }
async function load(){ try{ const d=await fetch(apiSite(API+"/sensors")).then(r=>r.json()); sensors=d.sensors||[]; draw(); }catch(e){} }
function draw(){ layer.clearLayers(); for(const s of sensors){ if(s.lat==null) continue; const v=s.last_value; const al=v!=null&&((s.min_alert!=null&&v<s.min_alert)||(s.max_alert!=null&&v>s.max_alert)); const old=s.last_at&&(Date.now()-new Date(s.last_at))>6*3600e3;
    const m=L.marker([s.lat,s.lon],{icon:L.divIcon({className:"",html:`<div class="sn-pin ${al?"al":""} ${old?"old":""}">${v!=null?`${(+v).toLocaleString(EN?"en-GB":"pt-PT",{maximumFractionDigits:1})}${s.unit||""}`:"—"}</div>`,iconSize:[40,26],iconAnchor:[20,13]}),zIndexOffset:700}); m.bindTooltip(`${s.name||s.id} · ${s.kind||""}${s.last_at?` · ${T.last} ${ago(s.last_at)} ${T.ago}`:" · "+T.noread}`); m.on("click",()=>open(s)); layer.addLayer(m); }
  if(sensors.length&&!map.hasLayer(layer)) layer.addTo(map); }
async function open(s){ const d=await fetch(`${API}/sensors/${encodeURIComponent(s.id)}/series`).then(r=>r.json()).catch(()=>({series:[]})); const ser=d.series||[]; const W=300,H=70; let svg=""; if(ser.length>1){ const vs=ser.map(x=>+x.value), y0=Math.min(...vs), y1=Math.max(...vs), yr=Math.max(1e-6,y1-y0); const t0=new Date(ser[0].at).getTime(), t1=new Date(ser[ser.length-1].at).getTime()||t0+1; const pts=ser.map(x=>`${(((new Date(x.at).getTime()-t0)/(t1-t0))*W).toFixed(1)},${(H-6-(+x.value-y0)/yr*(H-14)).toFixed(1)}`).join(" "); svg=`<svg viewBox="0 0 ${W} ${H}" width="100%" height="${H}" style="background:var(--night-2);border-radius:6px"><polyline points="${pts}" fill="none" stroke="var(--water)" stroke-width="1.5"/><text x="4" y="12" font-size="9" fill="var(--muted)">${y1}</text><text x="4" y="${H-2}" font-size="9" fill="var(--muted)">${y0}</text></svg>`; }
  const props={name:s.name||s.id,kind:s.kind,unit:s.unit,valor:s.last_value,ultima:s.last_at?String(s.last_at).slice(0,16).replace("T"," "):T.noread,alerta_min:s.min_alert,alerta_max:s.max_alert,leituras_7d:ser.length,brain_id:"sensor:"+s.id};
  if(window.showCard){ showCard(props,L.latLng(s.lat,s.lon),T.title); const body=document.getElementById("cbody"); if(body&&svg){ const div=document.createElement("div"); div.innerHTML=svg; body.insertBefore(div,body.children[1]||null); } } }
window.edrSensors={reload:load,register(){ const a=auth(); if(a.role!=="leader"){ toast&&toast(EN?"Leadership key required":"Precisa da chave de liderança"); return; } const id=prompt(T.id); if(!id) return; const name=prompt(T.name,id)||id; const kind=prompt(T.kind,"tanque")||""; const unit=prompt(T.unit,"%")||""; const mn=prompt(T.min,""); const mx=prompt(T.max,""); toast&&toast(T.place); map.once("click",async e=>{ const r=await fetch(API+"/sensors",{method:"POST",headers:hdr(),body:JSON.stringify({site:SITE_ID,id,name,kind,unit,lat:e.latlng.lat,lon:e.latlng.lng,min_alert:mn?+mn:null,max_alert:mx?+mx:null,actor:a.actor})}).then(r=>r.json()).catch(()=>({})); toast&&toast(r.ok?"✓":(r.error||"—")); load(); }); }};
load(); setInterval(load,120000);
})();
