// EdenRise tasks — work pinned to a place or an item: assignee, due date, priority, done with a photo. Bilingual, offline-tolerant.
(function(){
const API="https://edenrise-brain.edenrise.workers.dev";
const L_=(typeof LANG!=="undefined")?LANG:"pt"; const EN=L_==="en";
const T=EN?{tasks:"Tasks",open:"open",mine:"mine",all:"all",done:"done",newT:"New task",title:"What needs doing",detail:"Details (optional)",who:"Assign to",due:"Due",prio:"Priority",p:{baixa:"low",normal:"normal",alta:"high",urgente:"urgent"},save:"Create task",cancel:"Cancel",here:"Tap the map where the task is",markDone:"Mark done",doneQ:"Mark as done? You can add a photo of the result.",photoQ:"Add a photo of the finished work?",start:"Start",reopen:"Reopen",del:"Delete",delQ:"Delete this task?",overdue:"overdue",today:"today",noTasks:"No open tasks",signin:"Sign in with a team key to create tasks",created:"Task created",saved:"Saved",share:"WhatsApp",go:"go",by:"by",at:"on",st:{aberta:"open","em curso":"in progress",feita:"done",cancelada:"cancelled"},doneNote:"Result note (optional)",task:"Task",forItem:"for"}
:{tasks:"Tarefas",open:"abertas",mine:"minhas",all:"todas",done:"feitas",newT:"Nova tarefa",title:"O que é preciso fazer",detail:"Detalhes (opcional)",who:"Atribuir a",due:"Prazo",prio:"Prioridade",p:{baixa:"baixa",normal:"normal",alta:"alta",urgente:"urgente"},save:"Criar tarefa",cancel:"Cancelar",here:"Toque no mapa onde é a tarefa",markDone:"Marcar feita",doneQ:"Marcar como feita? Pode juntar uma foto do resultado.",photoQ:"Juntar uma foto do trabalho feito?",start:"Iniciar",reopen:"Reabrir",del:"Apagar",delQ:"Apagar esta tarefa?",overdue:"atrasada",today:"hoje",noTasks:"Sem tarefas abertas",signin:"Entre com a chave da equipa para criar tarefas",created:"Tarefa criada",saved:"Guardado",share:"WhatsApp",go:"ir",by:"por",at:"em",st:{aberta:"aberta","em curso":"em curso",feita:"feita",cancelada:"cancelada"},doneNote:"Nota do resultado (opcional)",task:"Tarefa",forItem:"para"};
const auth=()=>window.edrAuth||{key:"",role:"viewer",actor:""}; const hdr=()=>({"Content-Type":"application/json",...(auth().key?{"X-Role-Key":auth().key}:{})});
const PCOL={baixa:"#9fb789",normal:"#c9a227",alta:"#e07b39",urgente:"#d9534f"};
const css=document.createElement("style"); css.textContent=`
#tpanel{position:absolute;right:14px;top:58px;bottom:26px;width:min(400px,calc(100vw - 28px));z-index:1465;background:rgba(28,24,19,.97);backdrop-filter:blur(12px);border:1px solid var(--line-2);border-radius:14px;box-shadow:var(--sh);display:flex;flex-direction:column;overflow:hidden} #tpanel[hidden]{display:none}
#tpanel .hd{padding:12px 14px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:10px} #tpanel .hd h3{margin:0;font:600 15px var(--display);flex:1} #tpanel .hd button{border:0;background:transparent;color:var(--muted);font-size:16px;cursor:pointer}
#tpanel .bd{flex:1;overflow-y:auto;padding:10px 14px;display:flex;flex-direction:column;gap:8px;min-height:0} #tpanel .bd > *{flex-shrink:0}
#tpanel .tkind,#tpanel .tdraw{display:flex;gap:6px} #tpanel .tkind button,#tpanel .tdraw button{flex:1;min-height:42px;border-radius:10px;border:1px solid var(--line-2);background:transparent;color:var(--linen);font:600 12.5px var(--ui);cursor:pointer} #tpanel .tkind button.on{background:var(--straw);color:var(--bark);border-color:var(--straw)} #tpanel .tdraw[hidden]{display:none} #map .tk-catch{position:absolute;inset:0;z-index:640;cursor:crosshair;background:transparent;touch-action:none} #tpanel.drawing{max-height:none!important;height:auto!important;top:auto!important} #tpanel.drawing .hd,#tpanel.drawing .ft,#tpanel.drawing .bd > :not(#twhere):not(#tdraw){display:none!important} #tpanel.drawing .bd{padding:8px 10px} #tpanel .tdraw button.ok{flex:2;background:#5be0a0;color:#0b1a20;border-color:#5be0a0} #tpanel .tdraw button:disabled{opacity:.45} #tpanel .chips{display:flex;gap:5px;flex-wrap:wrap} #tpanel .chips button{font:500 11px var(--ui);padding:4px 9px;border-radius:999px;border:1px solid var(--line-2);background:transparent;color:var(--linen-2);cursor:pointer} #tpanel .chips button.on{border-color:var(--straw);color:var(--linen);background:var(--night-2)}
#tpanel .tk{border:1px solid var(--line-2);border-radius:10px;padding:9px 11px;display:grid;grid-template-columns:8px 1fr auto;gap:10px;align-items:start;cursor:pointer} #tpanel .tk:hover{border-color:var(--straw)} #tpanel .tk .bar{width:8px;border-radius:4px;align-self:stretch} #tpanel .tk b{font:600 13.5px var(--ui);display:block} #tpanel .tk small{color:var(--muted);font-size:11px;display:block;margin-top:2px} #tpanel .tk .ov{color:var(--ember);font-weight:700} #tpanel .tk.done{opacity:.55}
#tpanel .ft{padding:10px 12px;border-top:1px solid var(--line);display:flex;gap:6px} #tpanel .ft button{flex:1;padding:11px;border-radius:10px;border:0;font:700 13px var(--ui);cursor:pointer;background:var(--oak);color:var(--bark)} #tpanel .ft button.x{background:var(--night-2);color:var(--linen);flex:0 0 auto;padding:11px 14px}
#tpanel label{display:flex;flex-direction:column;gap:4px;font:500 11px var(--ui);color:var(--muted)} #tpanel input,#tpanel select,#tpanel textarea{padding:9px 10px;background:var(--bark);color:var(--linen);border:1px solid var(--line-2);border-radius:9px;font:13.5px var(--ui)} #tpanel textarea{min-height:56px;resize:vertical} #tpanel .g2{display:grid;grid-template-columns:1fr 1fr;gap:8px}
#tpanel .rows{display:flex;flex-direction:column;gap:5px} #tpanel .rows button{text-align:left;padding:10px 12px;border-radius:9px;border:1px solid var(--line-2);background:transparent;color:var(--linen);font:500 13px var(--ui);cursor:pointer} #tpanel .rows button:hover{border-color:var(--straw)}
.tk-pin{width:28px;height:28px;border-radius:8px;border:2px solid #fff;box-shadow:0 2px 8px rgba(0,0,0,.5);display:flex;align-items:center;justify-content:center;font:800 14px var(--ui);color:#111} .tk-pin.done{opacity:.5}
#appnav .tasks{display:inline-flex;align-items:center;gap:7px;margin-right:8px;background:var(--night-2);color:var(--linen);border:1px solid var(--line-2);border-radius:999px;padding:8px 14px;font:700 12px var(--display);letter-spacing:.06em;cursor:pointer} #appnav .tasks .n{background:var(--straw);color:var(--bark);border-radius:999px;padding:1px 7px;font-size:10.5px} #appnav .tasks .n.ov{background:var(--ember);color:#fff} #appnav .tasks:hover{border-color:var(--straw)} @media(max-width:700px){.nav .tasks span.t{display:none}#appnav .tasks{padding:8px 10px}}
@media(max-width:700px){ #tpanel{left:8px;right:8px;top:auto;bottom:8px;width:auto;max-height:70vh} }`;
document.head.appendChild(css);
const mapEl=document.getElementById("map"); const layer=L.layerGroup().addTo(map); let tasks=[], filter="open", panel=null;
/* area and route tasks: the shape lives in the task's own record (item "area:<key>", note kind "area"); the task keeps a pin at its centre */
const GEO=new Map(); try{ const c=JSON.parse(localStorage.getItem("edr_task_geo")||"{}"); for(const k in c) GEO.set(k,c[k]); }catch(e){}
function saveGeoCache(){ try{ const o={}; for(const [k,v] of GEO) o[k]=v; localStorage.setItem("edr_task_geo",JSON.stringify(o)); }catch(e){} }
const isArea=t=>t&&typeof t.feature_id==="string"&&t.feature_id.startsWith("area:");
async function loadGeo(){ const need=tasks.filter(t=>isArea(t)&&!GEO.has(t.feature_id)); await Promise.all(need.map(async t=>{ try{ const d=await fetch(`${API}/item/${encodeURIComponent(t.feature_id)}`).then(r=>r.json()); const n=(d.notes||[]).filter(x=>x.kind==="area").sort((a,b)=>String(b.at).localeCompare(String(a.at)))[0]; if(n) GEO.set(t.feature_id,JSON.parse(n.text)); }catch(e){} })); if(need.length) saveGeoCache(); }
function geoSize(g){ try{ if(!window.turf||!g) return ""; if(/Polygon/.test(g.type)){ const a=turf.area(g); return a>=10000?`${(a/10000).toFixed(2)} ha`:`${Math.round(a)} m²`; } const l=turf.length(g,{units:"meters"}); return l>=1000?`${(l/1000).toFixed(2)} km`:`${Math.round(l)} m`; }catch(e){ return ""; } }
let drawingTask=false;
const people=t=>String(t.assignee||"").split(",").map(x=>x.trim()).filter(Boolean);
const today=()=>new Date().toISOString().slice(0,10);
const isOver=t=>t.due&&t.status!=="feita"&&t.status!=="cancelada"&&t.due<today();
function pinIcon(t){ const c=PCOL[t.priority]||PCOL.normal; const done=t.status==="feita"; return L.divIcon({className:"",html:`<div class="tk-pin ${done?"done":""}" style="background:${isOver(t)?"#d9534f":c}">${done?"✓":"!"}</div>`,iconSize:[28,28],iconAnchor:[14,28]}); }
async function load(){ try{ const d=await fetch(API+"/tasks?status=all&site="+SITE_ID).then(r=>r.json()); tasks=d.tasks||[]; await loadGeo(); draw(); badge(); if(panel&&!panel.hidden) list(); }catch(e){} }
function draw(){ layer.clearLayers(); for(const t of tasks){ if(t.lat==null||t.status==="cancelada"||(t.status==="feita"&&filter!=="done")) continue; const g=isArea(t)&&GEO.get(t.feature_id); if(g){ const col=isOver(t)?"#d9534f":(PCOL[t.priority]||PCOL.normal); const sh=L.geoJSON({type:"Feature",geometry:g},{style:{color:col,weight:/Line/.test(g.type)?5:2.5,opacity:.9,dashArray:t.status==="feita"?null:"10 6",fillColor:col,fillOpacity:t.status==="feita"?.05:.12}}); sh.on("click",()=>{ if(!drawingTask) open(t); }); layer.addLayer(sh); } const m=L.marker([t.lat,t.lon],{icon:pinIcon(t),zIndexOffset:600}); m.on("click",()=>{ if(!drawingTask) open(t); }); m.bindTooltip(`${t.title}${t.assignee?" · "+t.assignee:""}${g?" · "+geoSize(g):""}`); layer.addLayer(m); } }
function badge(){ const b=document.getElementById("nav-tasks"); if(!b) return; const open=tasks.filter(t=>t.status==="aberta"||t.status==="em curso"); const ov=open.filter(isOver).length; b.querySelector(".n").textContent=open.length; b.querySelector(".n").classList.toggle("ov",ov>0); }
function ensurePanel(){ if(panel) return panel; panel=document.createElement("div"); panel.id="tpanel"; panel.hidden=true; mapEl.appendChild(panel); L.DomEvent.disableClickPropagation(panel); L.DomEvent.disableScrollPropagation(panel); return panel; }
function close(){ if(panel) panel.hidden=true; }
function list(){ const p=ensurePanel(); p.hidden=false; const me=auth().actor; const vis=tasks.filter(t=>filter==="all"?t.status!=="cancelada":filter==="done"?t.status==="feita":filter==="mine"?((people(t).includes(me)||t.created_by===me)&&t.status!=="feita"&&t.status!=="cancelada"):(t.status==="aberta"||t.status==="em curso"));
  p.innerHTML=`<div class="hd"><h3>✔ ${T.tasks}</h3><button id="tclose">✕</button></div><div class="bd"><div class="chips">${["open","mine","done","all"].map(k=>`<button data-f="${k}" class="${filter===k?"on":""}">${T[k]}</button>`).join("")}</div>
  ${vis.length?vis.map(t=>`<div class="tk ${t.status==="feita"?"done":""}" data-id="${t.id}"><span class="bar" style="background:${isOver(t)?"#d9534f":(PCOL[t.priority]||PCOL.normal)}"></span><div><b>${esc(t.title)}</b><small>${t.assignee?"→ "+esc(t.assignee)+" · ":""}${t.due?`<span class="${isOver(t)?"ov":""}">${t.due===today()?T.today:t.due}${isOver(t)?" · "+T.overdue:""}</span> · `:""}${T.st[t.status]||t.status}${isArea(t)?" · "+(/Line/.test((GEO.get(t.feature_id)||{}).type||"")?"〰 ":"⬠ ")+geoSize(GEO.get(t.feature_id)):(t.feature_id?" · "+esc(t.feature_id.split(":").pop()):"")}</small></div><span style="font:600 10.5px var(--mono);color:var(--straw)">${T.go} ↗</span></div>`).join(""):`<div style="color:var(--muted);font:13px var(--ui)">${T.noTasks}</div>`}</div>
  <div class="ft"><button id="tnew">+ ${T.newT}</button><button class="x" id="tclose2">${EN?"Close":"Fechar"}</button></div>`;
  p.querySelector("#tclose").onclick=close; p.querySelector("#tclose2").onclick=close; p.querySelectorAll("[data-f]").forEach(b=>b.onclick=()=>{ filter=b.dataset.f; draw(); list(); });
  p.querySelectorAll(".tk").forEach(el=>el.onclick=()=>open(tasks.find(t=>t.id===el.dataset.id))); p.querySelector("#tnew").onclick=()=>newTask(); }
function esc(s){ return String(s||"").replace(/[<>&]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;"}[c])); }
const LS={aceite:EN?"accepted":"aceite",bloqueada:EN?"blocked":"bloqueada",verificada:EN?"verified":"verificada"};
async function lifecycle(t){ let notes=[]; try{ const d=await fetch(`${API}/item/${encodeURIComponent("task:"+t.id)}`).then(r=>r.json()); notes=(d.notes||[]).sort((x,y)=>String(x.at).localeCompare(String(y.at))); }catch(e){}
  const last=k=>notes.filter(n=>n.kind===k).pop(); const bl=last("bloqueio"), ub=last("desbloqueio"), ve=last("verificacao"), ac=last("aceite");
  let state=t.status; if(t.status==="feita"&&ve&&(!t.done_at||ve.at>=t.done_at)) state="verificada"; else if((t.status==="aberta"||t.status==="em curso")&&bl&&(!ub||bl.at>ub.at)) state="bloqueada"; else if(t.status==="aberta"&&ac) state="aceite";
  const custo=notes.filter(n=>n.kind==="custo").map(n=>n.text); return {state,notes,bl,ve,ac,custo}; }
async function note(fid,kind,text){ const a=auth(); try{ await fetch(`${API}/item/${encodeURIComponent(fid)}/notes`,{method:"POST",headers:hdr(),body:JSON.stringify({text,kind,actor:a.actor,site:SITE_ID})}); }catch(e){} }
function open(t){ const p=ensurePanel(); p.hidden=false; const a=auth(); const can=a.role==="leader"||a.role==="field"; const done=t.status==="feita"; const tg=isArea(t)&&GEO.get(t.feature_id); if(tg){ try{ map.fitBounds(L.geoJSON(tg).getBounds(),{padding:[60,60],maxZoom:19}); }catch(e){} } else if(t.lat!=null) map.setView([t.lat,t.lon],Math.max(map.getZoom(),18));
  const wa=`https://wa.me/?text=${encodeURIComponent(`${T.task}: ${t.title}${t.assignee?" → "+t.assignee:""}${t.due?" · "+T.due+" "+t.due:""}\n${location.origin}${location.pathname}#task=${t.id}`)}`;
  p.innerHTML=`<div class="hd"><h3>${esc(t.title)}</h3><button id="tclose">✕</button></div><div class="bd">
  <div style="font:12px var(--ui);color:var(--linen-2)"><span id="tstate" style="display:inline-block;padding:2px 8px;border-radius:999px;background:${isOver(t)?"#d9534f":(PCOL[t.priority]||PCOL.normal)};color:#111;font:600 10px var(--mono);letter-spacing:.08em;text-transform:uppercase">${T.st[t.status]||t.status}${isOver(t)?" · "+T.overdue:""}</span> · ${T.p[t.priority]||t.priority}${t.assignee?" · → <b>"+esc(t.assignee)+"</b>":""}${t.due?" · "+T.due+" "+t.due:""}</div>
  ${t.detail?`<div style="font:13.5px var(--ui);white-space:pre-wrap">${esc(t.detail)}</div>`:""}
  <div style="font:11.5px var(--ui);color:var(--muted)">${T.by} ${esc(t.created_by||"—")} ${T.at} ${String(t.created_at).slice(0,10)}${tg?` · ${/Line/.test(tg.type)?"〰 "+(EN?"route":"percurso"):"⬠ "+(EN?"area":"área")} ${geoSize(tg)}`:(t.feature_id?" · "+T.forItem+" "+esc(t.feature_id):"")}${done?` · ✓ ${esc(t.done_by||"")} ${String(t.done_at||"").slice(0,10)}${t.done_note?" · "+esc(t.done_note):""}`:""}</div>
  <div id="tbrain"></div>
  <div class="rows" id="tacts">${can&&!done?`<button id="tdone" style="border-color:var(--oak);color:var(--oak)">✓ ${T.markDone}</button>`:""}${can&&t.status==="aberta"?`<button id="taccept">👍 ${EN?"Accept":"Aceitar"}</button><button id="tstart">▶ ${T.start}</button>`:""}${can&&!done?`<button id="tblock" style="border-color:var(--ember)">⛔ ${EN?"Blocked":"Bloqueada"}</button>`:""}${a.role==="leader"&&done?`<button id="tverify" style="border-color:var(--straw);color:var(--straw)">✔✔ ${EN?"Verify":"Verificar"}</button>`:""}${can&&done?`<button id="treopen">↶ ${T.reopen}</button>`:""}${t.feature_id&&!isArea(t)?`<button id="titem">📍 ${esc(t.feature_id)}</button>`:""}<a href="${wa}" target="_blank" style="text-align:left;padding:10px 12px;border-radius:9px;border:1px solid var(--line-2);color:var(--linen);font:500 13px var(--ui);text-decoration:none">💬 ${T.share}</a>${a.role==="leader"?`<button id="tdel" style="color:var(--ember);border-color:var(--ember)">🗑 ${T.del}</button>`:""}</div></div>
  <div class="ft"><button class="x" id="tback" style="flex:1">← ${T.tasks}</button></div>`;
  p.querySelector("#tclose").onclick=close; p.querySelector("#tback").onclick=list;
  if(window.edrItem) edrItem("task:"+t.id, p.querySelector("#tbrain"), {latlng: t.lat!=null?L.latLng(t.lat,t.lon):null});
  const patch=async(body)=>{ const r=await fetch(API+"/tasks/"+t.id,{method:"PATCH",headers:hdr(),body:JSON.stringify({...body,actor:a.actor})}).then(r=>r.json()).catch(()=>({})); if(r.ok){ toast&&toast(T.saved); await load(); open(tasks.find(x=>x.id===t.id)||t); } else toast&&toast(r.need||r.error||"—"); };
  const q=s=>p.querySelector(s);
  if(q("#tdone")) q("#tdone").onclick=()=>completeForm();
  const completeForm=()=>{ const box=document.createElement("div"); box.className="tkdone"; box.innerHTML=`<label>${T.doneNote}<textarea id="cnote" rows="2"></textarea></label><div class="g2"><label>${EN?"Parts used":"Peças usadas"}<input id="cparts" placeholder="${EN?"e.g. 6204 bearing":"ex.: rolamento 6204"}"></label><label>${EN?"Parts cost (€)":"Custo peças (€)"}<input id="ceur" type="number" step="0.01" inputmode="decimal"></label></div><div class="g2"><label>${EN?"Labour (hours)":"Mão-de-obra (horas)"}<input id="chrs" type="number" step="0.25" inputmode="decimal"></label><label>${EN?"Who did it":"Quem fez"}<input id="cwho" value="${esc(a.actor)}"></label></div><div class="rows"><button id="cok" style="border-color:var(--oak);color:var(--oak)">✓ ${T.markDone}</button><button id="ccancel">${T.cancel}</button></div>`;
    q("#tacts").replaceWith(box); box.querySelector("#ccancel").onclick=()=>open(t);
    box.querySelector("#cok").onclick=async()=>{ const nt=box.querySelector("#cnote").value.trim(), parts=box.querySelector("#cparts").value.trim(), eur=parseFloat(box.querySelector("#ceur").value), hrs=parseFloat(box.querySelector("#chrs").value), who=box.querySelector("#cwho").value.trim();
      const cost=[]; if(parts) cost.push(`${EN?"parts":"peças"}: ${parts}`); if(eur>0) cost.push(`${EN?"parts cost":"custo peças"}: ${eur.toFixed(2)} €`); if(hrs>0) cost.push(`${EN?"labour":"mão-de-obra"}: ${hrs} h`); if(who) cost.push(`${EN?"by":"por"}: ${who}`);
      await patch({status:"feita",done_note:nt}); if(cost.length){ const txt=`${EN?"Cost":"Custo"} · ${cost.join(" · ")} · ${t.title}`; await note("task:"+t.id,"custo",txt); if(t.feature_id) await note(t.feature_id,"custo",txt); }
      if(confirm(T.photoQ)){ const b=p.querySelector("#tbrain #mbp"); if(b) b.click(); } };
    box.querySelector("#cnote").focus(); };
  if(q("#taccept")) q("#taccept").onclick=async()=>{ await note("task:"+t.id,"aceite",`${EN?"Accepted by":"Aceite por"} ${a.actor}`); await patch({assignee:t.assignee||a.actor}); };
  if(q("#tblock")) q("#tblock").onclick=async()=>{ const why=prompt(EN?"What is blocking it?":"O que está a bloquear?",""); if(why===null||!why.trim()) return; await note("task:"+t.id,"bloqueio",why.trim()); open(t); };
  if(q("#tverify")) q("#tverify").onclick=async()=>{ const nt=prompt(EN?"Verification note (what you checked)":"Nota de verificação (o que confirmaste)","")||""; await note("task:"+t.id,"verificacao",`${EN?"Verified by":"Verificado por"} ${a.actor}${nt?" · "+nt:""}`); if(t.feature_id) await note(t.feature_id,"servico",`${EN?"Verified":"Verificado"}: ${t.title}${nt?" · "+nt:""}`); toast&&toast(EN?"Verified":"Verificado"); open(t); };
  lifecycle(t).then(L=>{ const pill=p.querySelector("#tstate"); if(pill&&L.state!==t.status){ pill.textContent=(LS[L.state]||L.state)+(isOver(t)?" · "+T.overdue:""); pill.style.background=L.state==="verificada"?"#5be0a0":L.state==="bloqueada"?"#d9534f":L.state==="aceite"?"#9fb789":pill.style.background; }
    if(L.state==="bloqueada"&&q("#tblock")){ q("#tblock").textContent=`▶ ${EN?"Unblock":"Desbloquear"}`; q("#tblock").style.borderColor="var(--oak)"; q("#tblock").onclick=async()=>{ await note("task:"+t.id,"desbloqueio",`${EN?"Unblocked by":"Desbloqueada por"} ${a.actor}`); open(t); }; }
    if(L.custo.length){ const d=document.createElement("div"); d.style.cssText="font:12px var(--ui);color:var(--straw)"; d.textContent="💶 "+L.custo.map(c=>c.replace(/^(Custo|Cost) · /,"").replace(/ · [^·]*$/,"")).join(" | "); p.querySelector("#tbrain").before(d); } });
  if(q("#tstart")) q("#tstart").onclick=()=>patch({status:"em curso",assignee:t.assignee||a.actor}); if(q("#treopen")) q("#treopen").onclick=()=>patch({status:"aberta"});
  if(q("#tdel")) q("#tdel").onclick=async()=>{ if(!confirm(T.delQ)) return; await fetch(API+"/tasks/"+t.id+"?actor="+encodeURIComponent(a.actor),{method:"DELETE",headers:hdr()}); await load(); list(); };
  if(q("#titem")) q("#titem").onclick=()=>{ if(t.lat!=null) map.setView([t.lat,t.lon],19); const id=t.feature_id; map.eachLayer(l=>{ if(l.feature&&l.__ed&&l.feature.properties.id===id) l.fire("click",{latlng:L.latLng(t.lat,t.lon)}); }); }; }
function newTask(pre){ const a=auth(); if(a.role==="viewer"){ toast&&toast(T.signin); return; } pre=pre||{}; const p=ensurePanel(); p.hidden=false;
  p.innerHTML=`<div class="hd"><h3>+ ${T.newT}</h3><button id="tclose">✕</button></div><div class="bd"><label>${T.title}<input id="tt" autofocus value="${esc(pre.title||"")}"></label><label>${T.detail}<textarea id="td">${esc(pre.detail||"")}</textarea></label><div class="g2"><label>${T.who}<input id="ta" list="tpeople" value="${esc(pre.assignee||"")}"><datalist id="tpeople">${[...new Set(tasks.flatMap(t=>[t.assignee,t.created_by]).filter(Boolean))].map(n=>`<option value="${esc(n)}">`).join("")}</datalist></label><label>${T.due}<input id="tdu" type="date"></label></div><label>${T.prio}<select id="tp">${Object.entries(T.p).map(([k,v])=>`<option value="${k}" ${k==="normal"?"selected":""}>${v}</option>`).join("")}</select></label>
  <div class="tkind">${[["pt","📍 "+(EN?"Point":"Ponto")],["area","⬠ "+(EN?"Area":"Área")],["route","〰 "+(EN?"Route":"Percurso")]].map(([k,l])=>`<button data-k="${k}" class="${k==="pt"?"on":""}">${l}</button>`).join("")}</div><div style="font:12px var(--ui);color:var(--muted)" id="twhere">${pre.latlng?`📍 ${pre.latlng.lat.toFixed(5)}, ${pre.latlng.lng.toFixed(5)}${pre.feature_id?" · "+esc(pre.feature_id):""}`:T.here}</div><div class="tdraw" id="tdraw" hidden><button data-d="undo" aria-label="${EN?"Undo last point":"Anular último ponto"}">↶</button><button data-d="done" class="ok"></button><button data-d="clear" aria-label="${EN?"Clear":"Limpar"}">✕</button></div><div style="font:11px var(--ui);color:var(--muted)">${EN?"Several people: separate names with commas.":"Várias pessoas: separa os nomes com vírgulas."}</div></div>
  <div class="ft"><button id="tsave">${T.save}</button><button class="x" id="tcancel">${T.cancel}</button></div>`;
  const tidy=()=>{ map.off("click",pick); catchOff(); mapEl.classList.remove("ed-draw"); map.doubleClickZoom.enable(); slim(false); clearDots(); if(preview){ map.removeLayer(preview); preview=null; } };
  p.querySelector("#tclose").onclick=()=>{ tidy(); close(); }; p.querySelector("#tcancel").onclick=()=>{ tidy(); list(); };
  let ll=pre.latlng||null; let kind="pt", shape=null, verts=[], preview=null; const where=p.querySelector("#twhere"), dbar=p.querySelector("#tdraw");
  const pick=e=>{ if(kind!=="pt") return; ll=e.latlng; where.textContent=`📍 ${ll.lat.toFixed(5)}, ${ll.lng.toFixed(5)}`; mapEl.classList.remove("ed-draw"); map.off("click",pick); };
  const redraw=()=>{ clearDots(); if(preview){ map.removeLayer(preview); preview=null; } if(!verts.length){ const b=dbar.querySelector('[data-d="done"]'); b.disabled=true; b.textContent=EN?"Finish":"Terminar"; return; } const col="#c9a227"; preview=kind==="area"&&verts.length>2?L.polygon(verts,{color:col,weight:3,dashArray:"8 6",fillOpacity:.12,interactive:false}):L.polyline(verts,{color:col,weight:kind==="route"?5:3,dashArray:"8 6",interactive:false}); verts.forEach(v=>L.circleMarker(v,{radius:6,color:"#fff",weight:2,fillColor:col,fillOpacity:1,interactive:false}).addTo(map)); preview.addTo(map);
    const need=kind==="area"?3:2; const b=dbar.querySelector('[data-d="done"]'); b.disabled=verts.length<need; b.textContent=(EN?"Finish ":"Terminar ")+(kind==="area"?(EN?"area":"área"):(EN?"route":"percurso"))+` (${verts.length})`; };
  let catcher=null; const catchOn=()=>{ if(catcher) return; catcher=document.createElement("div"); catcher.className="tk-catch"; mapEl.appendChild(catcher); let sx=0,sy=0; catcher.addEventListener("pointerdown",ev=>{ sx=ev.clientX; sy=ev.clientY; }); catcher.addEventListener("click",ev=>{ if(Math.hypot(ev.clientX-sx,ev.clientY-sy)>8) return; vertex({latlng:map.mouseEventToLatLng(ev)}); }); };
  const catchOff=()=>{ if(catcher){ catcher.remove(); catcher=null; } };
  const vertex=e=>{ if(kind==="pt") return; verts.push(e.latlng); redraw(); where.textContent=`${kind==="area"?"⬠":"〰"} ${verts.length} ${EN?"points — tap the map to add":"pontos — toca no mapa para acrescentar"}`; };
  const clearDots=()=>{ map.eachLayer(l=>{ if(l instanceof L.CircleMarker&&l.options&&l.options.interactive===false&&l.options.fillColor==="#c9a227") map.removeLayer(l); }); };
  const SLIM=matchMedia("(max-width:700px), ((pointer:coarse) and (max-width:1366px))"); const slim=on=>{ p.classList.toggle("drawing",on&&SLIM.matches); drawingTask=!!on; };
  const stopDraw=()=>{ catchOff(); mapEl.classList.remove("ed-draw"); map.doubleClickZoom.enable(); slim(false); };
  p.querySelectorAll(".tkind [data-k]").forEach(b=>b.onclick=()=>{ kind=b.dataset.k; p.querySelectorAll(".tkind button").forEach(x=>x.classList.toggle("on",x===b)); verts=[]; shape=null; clearDots(); if(preview){ map.removeLayer(preview); preview=null; } map.off("click",pick); stopDraw();
    if(kind==="pt"){ dbar.hidden=true; where.textContent=ll?`📍 ${ll.lat.toFixed(5)}, ${ll.lng.toFixed(5)}`:T.here; if(!ll){ mapEl.classList.add("ed-draw"); setTimeout(()=>map.on("click",pick),0); } return; }
    dbar.hidden=false; slim(true); where.textContent=EN?"Tap the map to draw the "+(kind==="area"?"area":"route"):"Toca no mapa para desenhar "+(kind==="area"?"a área":"o percurso"); mapEl.classList.add("ed-draw"); map.doubleClickZoom.disable(); catchOn(); redraw(); });
  dbar.querySelector('[data-d="undo"]').onclick=()=>{ verts.pop(); clearDots(); redraw(); };
  dbar.querySelector('[data-d="clear"]').onclick=()=>{ verts=[]; shape=null; clearDots(); redraw(); };
  dbar.querySelector('[data-d="done"]').onclick=()=>{ const c=verts.map(v=>[+v.lng.toFixed(7),+v.lat.toFixed(7)]); shape=kind==="area"?{type:"Polygon",coordinates:[[...c,c[0]]]}:{type:"LineString",coordinates:c}; stopDraw(); dbar.hidden=true;
    try{ const mid=kind==="area"?turf.centroid(shape).geometry.coordinates:turf.along(turf.lineString(c),turf.length(turf.lineString(c))/2).geometry.coordinates; ll=L.latLng(mid[1],mid[0]); }catch(e){ ll=verts[0]; }
    where.textContent=`${kind==="area"?"⬠ "+(EN?"area":"área"):"〰 "+(EN?"route":"percurso")} · ${geoSize(shape)} · ${verts.length} ${EN?"points":"pontos"}`; };
  if(!ll){ mapEl.classList.add("ed-draw"); setTimeout(()=>map.on("click",pick),0); }
  p.querySelector("#tsave").onclick=async()=>{ const title=p.querySelector("#tt").value.trim(); if(!title){ p.querySelector("#tt").focus(); return; } if(kind!=="pt"&&!shape){ toast&&toast(EN?"Finish the drawing first":"Termina primeiro o desenho"); return; } const areaKey=shape?"area:"+Date.now().toString(36)+Math.random().toString(36).slice(2,6):null; tidy();
    const r=await fetch(API+"/tasks",{method:"POST",headers:hdr(),body:JSON.stringify({site:SITE_ID,title,detail:p.querySelector("#td").value.trim(),assignee:p.querySelector("#ta").value.trim(),due:p.querySelector("#tdu").value||null,priority:p.querySelector("#tp").value,lon:ll?ll.lng:null,lat:ll?ll.lat:null,feature_id:areaKey||pre.feature_id||null,actor:a.actor})}).then(r=>r.json()).catch(()=>({}));
    if(r.ok&&areaKey){ GEO.set(areaKey,shape); saveGeoCache(); await note(areaKey,"area",JSON.stringify(shape)); }
    if(r.ok){ toast&&toast(T.created); if(pre.feature_id) note(pre.feature_id,"atualizacao",`→ ${T.task} ${r.id}: ${title}`); await load(); open(tasks.find(t=>t.id===r.id)); } else toast&&toast(r.error||"—"); }; }
window.edrTasks={list,newTask,open:(id)=>{ const t=tasks.find(x=>x.id===id); if(t) open(t); },reload:load,all:()=>tasks,lifecycle};
// nav pill
(function mk(n){ const nav=document.getElementById("appnav"); const edit=document.getElementById("nav-edit"); if(!nav||!edit){ if((n||0)<40) setTimeout(()=>mk((n||0)+1),150); return; } if(document.getElementById("nav-tasks")) return; const b=document.createElement("button"); b.className="tasks"; b.id="nav-tasks"; b.innerHTML=`✔ <span class="t">${T.tasks.toUpperCase()}</span> <span class="n">0</span>`; b.onclick=()=>{ if(panel&&!panel.hidden) close(); else list(); }; edit.parentNode.insertBefore(b,edit); badge(); })();
load(); setInterval(load,60000);
if(/[#&]task=([^&]+)/.test(location.hash)){ const id=location.hash.match(/task=([^&]+)/)[1]; setTimeout(()=>{ const t=tasks.find(x=>x.id===id); if(t) open(t); },1500); }
})();
