// EdenRise tasks — work pinned to a place or an item: assignee, due date, priority, done with a photo. Bilingual, offline-tolerant.
(function(){
const API="https://edenrise-brain.edenrise.workers.dev";
const L_=(typeof LANG!=="undefined")?LANG:"pt"; const EN=L_==="en";
const T=EN?{tasks:"Tasks",open:"open",mine:"mine",all:"all",done:"done",newT:"New task",title:"What needs doing",detail:"Details (optional)",who:"Assign to",due:"Due",prio:"Priority",p:{baixa:"low",normal:"normal",alta:"high",urgente:"urgent"},save:"Create task",cancel:"Cancel",here:"Tap the map where the task is",markDone:"Mark done",doneQ:"Mark as done? You can add a photo of the result.",photoQ:"Add a photo of the finished work?",start:"Start",reopen:"Reopen",del:"Delete",delQ:"Delete this task?",overdue:"overdue",today:"today",noTasks:"No open tasks",signin:"Sign in with a team key to create tasks",created:"Task created",saved:"Saved",share:"WhatsApp",go:"go",by:"by",at:"on",st:{aberta:"open","em curso":"in progress",feita:"done",cancelada:"cancelled"},doneNote:"Result note (optional)",task:"Task",forItem:"for"}
:{tasks:"Tarefas",open:"abertas",mine:"minhas",all:"todas",done:"feitas",newT:"Nova tarefa",title:"O que é preciso fazer",detail:"Detalhes (opcional)",who:"Atribuir a",due:"Prazo",prio:"Prioridade",p:{baixa:"baixa",normal:"normal",alta:"alta",urgente:"urgente"},save:"Criar tarefa",cancel:"Cancelar",here:"Toque no mapa onde é a tarefa",markDone:"Marcar feita",doneQ:"Marcar como feita? Pode juntar uma foto do resultado.",photoQ:"Juntar uma foto do trabalho feito?",start:"Iniciar",reopen:"Reabrir",del:"Apagar",delQ:"Apagar esta tarefa?",overdue:"atrasada",today:"hoje",noTasks:"Sem tarefas abertas",signin:"Entre com a chave da equipa para criar tarefas",created:"Tarefa criada",saved:"Guardado",share:"WhatsApp",go:"ir",by:"por",at:"em",st:{aberta:"aberta","em curso":"em curso",feita:"feita",cancelada:"cancelada"},doneNote:"Nota do resultado (opcional)",task:"Tarefa",forItem:"para"};
const auth=()=>window.edrAuth||{key:"",role:"viewer",actor:""}; const hdr=()=>({"Content-Type":"application/json",...(auth().key?{"X-Role-Key":auth().key}:{})});
const PCOL={baixa:"#9fb789",normal:"#c9a227",alta:"#e07b39",urgente:"#d9534f"};
const css=document.createElement("style"); css.textContent=`
#tpanel{position:absolute;right:14px;top:58px;bottom:26px;width:min(400px,calc(100vw - 28px));z-index:1465;background:rgba(28,24,19,.97);backdrop-filter:blur(12px);border:1px solid var(--line-2);border-radius:14px;box-shadow:var(--sh);display:flex;flex-direction:column;overflow:hidden} #tpanel[hidden]{display:none}
#tpanel .hd{padding:12px 14px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:10px} #tpanel .hd h3{margin:0;font:600 15px var(--display);flex:1} #tpanel .hd button{border:0;background:transparent;color:var(--muted);font-size:16px;cursor:pointer}
#tpanel .bd{flex:1;overflow-y:auto;padding:10px 14px;display:flex;flex-direction:column;gap:8px} #tpanel .chips{display:flex;gap:5px;flex-wrap:wrap} #tpanel .chips button{font:500 11px var(--ui);padding:4px 9px;border-radius:999px;border:1px solid var(--line-2);background:transparent;color:var(--linen-2);cursor:pointer} #tpanel .chips button.on{border-color:var(--straw);color:var(--linen);background:var(--night-2)}
#tpanel .tk{border:1px solid var(--line-2);border-radius:10px;padding:9px 11px;display:grid;grid-template-columns:8px 1fr auto;gap:10px;align-items:start;cursor:pointer} #tpanel .tk:hover{border-color:var(--straw)} #tpanel .tk .bar{width:8px;border-radius:4px;align-self:stretch} #tpanel .tk b{font:600 13.5px var(--ui);display:block} #tpanel .tk small{color:var(--muted);font-size:11px;display:block;margin-top:2px} #tpanel .tk .ov{color:var(--ember);font-weight:700} #tpanel .tk.done{opacity:.55}
#tpanel .ft{padding:10px 12px;border-top:1px solid var(--line);display:flex;gap:6px} #tpanel .ft button{flex:1;padding:11px;border-radius:10px;border:0;font:700 13px var(--ui);cursor:pointer;background:var(--oak);color:var(--bark)} #tpanel .ft button.x{background:var(--night-2);color:var(--linen);flex:0 0 auto;padding:11px 14px}
#tpanel label{display:flex;flex-direction:column;gap:4px;font:500 11px var(--ui);color:var(--muted)} #tpanel input,#tpanel select,#tpanel textarea{padding:9px 10px;background:var(--bark);color:var(--linen);border:1px solid var(--line-2);border-radius:9px;font:13.5px var(--ui)} #tpanel textarea{min-height:56px;resize:vertical} #tpanel .g2{display:grid;grid-template-columns:1fr 1fr;gap:8px}
#tpanel .rows{display:flex;flex-direction:column;gap:5px} #tpanel .rows button{text-align:left;padding:10px 12px;border-radius:9px;border:1px solid var(--line-2);background:transparent;color:var(--linen);font:500 13px var(--ui);cursor:pointer} #tpanel .rows button:hover{border-color:var(--straw)}
.tk-pin{width:28px;height:28px;border-radius:8px;border:2px solid #fff;box-shadow:0 2px 8px rgba(0,0,0,.5);display:flex;align-items:center;justify-content:center;font:800 14px var(--ui);color:#111} .tk-pin.done{opacity:.5}
#appnav .tasks{display:inline-flex;align-items:center;gap:7px;margin-right:8px;background:var(--night-2);color:var(--linen);border:1px solid var(--line-2);border-radius:999px;padding:8px 14px;font:700 12px var(--display);letter-spacing:.06em;cursor:pointer} #appnav .tasks .n{background:var(--straw);color:var(--bark);border-radius:999px;padding:1px 7px;font-size:10.5px} #appnav .tasks .n.ov{background:var(--ember);color:#fff} #appnav .tasks:hover{border-color:var(--straw)} @media(max-width:700px){.nav .tasks span.t{display:none}#appnav .tasks{padding:8px 10px}}
@media(max-width:700px){ #tpanel{left:8px;right:8px;top:auto;bottom:8px;width:auto;max-height:70vh} }`;
document.head.appendChild(css);
const mapEl=document.getElementById("map"); const layer=L.layerGroup().addTo(map); let tasks=[], filter="open", panel=null;
const today=()=>new Date().toISOString().slice(0,10);
const isOver=t=>t.due&&t.status!=="feita"&&t.status!=="cancelada"&&t.due<today();
function pinIcon(t){ const c=PCOL[t.priority]||PCOL.normal; const done=t.status==="feita"; return L.divIcon({className:"",html:`<div class="tk-pin ${done?"done":""}" style="background:${isOver(t)?"#d9534f":c}">${done?"✓":"!"}</div>`,iconSize:[28,28],iconAnchor:[14,28]}); }
async function load(){ try{ const d=await fetch(API+"/tasks?status=all&site="+SITE_ID).then(r=>r.json()); tasks=d.tasks||[]; draw(); badge(); if(panel&&!panel.hidden) list(); }catch(e){} }
function draw(){ layer.clearLayers(); for(const t of tasks){ if(t.lat==null||t.status==="cancelada"||(t.status==="feita"&&filter!=="done")) continue; const m=L.marker([t.lat,t.lon],{icon:pinIcon(t),zIndexOffset:600}); m.on("click",()=>open(t)); m.bindTooltip(`${t.title}${t.assignee?" · "+t.assignee:""}`); layer.addLayer(m); } }
function badge(){ const b=document.getElementById("nav-tasks"); if(!b) return; const open=tasks.filter(t=>t.status==="aberta"||t.status==="em curso"); const ov=open.filter(isOver).length; b.querySelector(".n").textContent=open.length; b.querySelector(".n").classList.toggle("ov",ov>0); }
function ensurePanel(){ if(panel) return panel; panel=document.createElement("div"); panel.id="tpanel"; panel.hidden=true; mapEl.appendChild(panel); L.DomEvent.disableClickPropagation(panel); L.DomEvent.disableScrollPropagation(panel); return panel; }
function close(){ if(panel) panel.hidden=true; }
function list(){ const p=ensurePanel(); p.hidden=false; const me=auth().actor; const vis=tasks.filter(t=>filter==="all"?t.status!=="cancelada":filter==="done"?t.status==="feita":filter==="mine"?((t.assignee===me||t.created_by===me)&&t.status!=="feita"&&t.status!=="cancelada"):(t.status==="aberta"||t.status==="em curso"));
  p.innerHTML=`<div class="hd"><h3>✔ ${T.tasks}</h3><button id="tclose">✕</button></div><div class="bd"><div class="chips">${["open","mine","done","all"].map(k=>`<button data-f="${k}" class="${filter===k?"on":""}">${T[k]}</button>`).join("")}</div>
  ${vis.length?vis.map(t=>`<div class="tk ${t.status==="feita"?"done":""}" data-id="${t.id}"><span class="bar" style="background:${isOver(t)?"#d9534f":(PCOL[t.priority]||PCOL.normal)}"></span><div><b>${esc(t.title)}</b><small>${t.assignee?"→ "+esc(t.assignee)+" · ":""}${t.due?`<span class="${isOver(t)?"ov":""}">${t.due===today()?T.today:t.due}${isOver(t)?" · "+T.overdue:""}</span> · `:""}${T.st[t.status]||t.status}${t.feature_id?" · "+esc(t.feature_id.split(":").pop()):""}</small></div><span style="font:600 10.5px var(--mono);color:var(--straw)">${T.go} ↗</span></div>`).join(""):`<div style="color:var(--muted);font:13px var(--ui)">${T.noTasks}</div>`}</div>
  <div class="ft"><button id="tnew">+ ${T.newT}</button><button class="x" id="tclose2">${EN?"Close":"Fechar"}</button></div>`;
  p.querySelector("#tclose").onclick=close; p.querySelector("#tclose2").onclick=close; p.querySelectorAll("[data-f]").forEach(b=>b.onclick=()=>{ filter=b.dataset.f; draw(); list(); });
  p.querySelectorAll(".tk").forEach(el=>el.onclick=()=>open(tasks.find(t=>t.id===el.dataset.id))); p.querySelector("#tnew").onclick=()=>newTask(); }
function esc(s){ return String(s||"").replace(/[<>&]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;"}[c])); }
function open(t){ const p=ensurePanel(); p.hidden=false; const a=auth(); const can=a.role==="leader"||a.role==="field"; const done=t.status==="feita"; if(t.lat!=null) map.setView([t.lat,t.lon],Math.max(map.getZoom(),18));
  const wa=`https://wa.me/?text=${encodeURIComponent(`${T.task}: ${t.title}${t.assignee?" → "+t.assignee:""}${t.due?" · "+T.due+" "+t.due:""}\n${location.origin}${location.pathname}#task=${t.id}`)}`;
  p.innerHTML=`<div class="hd"><h3>${esc(t.title)}</h3><button id="tclose">✕</button></div><div class="bd">
  <div style="font:12px var(--ui);color:var(--linen-2)"><span style="display:inline-block;padding:2px 8px;border-radius:999px;background:${isOver(t)?"#d9534f":(PCOL[t.priority]||PCOL.normal)};color:#111;font:600 10px var(--mono);letter-spacing:.08em;text-transform:uppercase">${T.st[t.status]||t.status}${isOver(t)?" · "+T.overdue:""}</span> · ${T.p[t.priority]||t.priority}${t.assignee?" · → <b>"+esc(t.assignee)+"</b>":""}${t.due?" · "+T.due+" "+t.due:""}</div>
  ${t.detail?`<div style="font:13.5px var(--ui);white-space:pre-wrap">${esc(t.detail)}</div>`:""}
  <div style="font:11.5px var(--ui);color:var(--muted)">${T.by} ${esc(t.created_by||"—")} ${T.at} ${String(t.created_at).slice(0,10)}${t.feature_id?" · "+T.forItem+" "+esc(t.feature_id):""}${done?` · ✓ ${esc(t.done_by||"")} ${String(t.done_at||"").slice(0,10)}${t.done_note?" · "+esc(t.done_note):""}`:""}</div>
  <div id="tbrain"></div>
  <div class="rows">${can&&!done?`<button id="tdone" style="border-color:var(--oak);color:var(--oak)">✓ ${T.markDone}</button>`:""}${can&&t.status==="aberta"?`<button id="tstart">▶ ${T.start}</button>`:""}${can&&done?`<button id="treopen">↶ ${T.reopen}</button>`:""}${t.feature_id?`<button id="titem">📍 ${esc(t.feature_id)}</button>`:""}<a href="${wa}" target="_blank" style="text-align:left;padding:10px 12px;border-radius:9px;border:1px solid var(--line-2);color:var(--linen);font:500 13px var(--ui);text-decoration:none">💬 ${T.share}</a>${a.role==="leader"?`<button id="tdel" style="color:var(--ember);border-color:var(--ember)">🗑 ${T.del}</button>`:""}</div></div>
  <div class="ft"><button class="x" id="tback" style="flex:1">← ${T.tasks}</button></div>`;
  p.querySelector("#tclose").onclick=close; p.querySelector("#tback").onclick=list;
  if(window.edrItem) edrItem("task:"+t.id, p.querySelector("#tbrain"), {latlng: t.lat!=null?L.latLng(t.lat,t.lon):null});
  const patch=async(body)=>{ const r=await fetch(API+"/tasks/"+t.id,{method:"PATCH",headers:hdr(),body:JSON.stringify({...body,actor:a.actor})}).then(r=>r.json()).catch(()=>({})); if(r.ok){ toast&&toast(T.saved); await load(); open(tasks.find(x=>x.id===t.id)||t); } else toast&&toast(r.need||r.error||"—"); };
  const q=s=>p.querySelector(s);
  if(q("#tdone")) q("#tdone").onclick=async()=>{ if(!confirm(T.doneQ)) return; const note=prompt(T.doneNote,"")||""; await patch({status:"feita",done_note:note}); if(confirm(T.photoQ)){ const b=p.querySelector("#tbrain #mbp"); if(b) b.click(); } };
  if(q("#tstart")) q("#tstart").onclick=()=>patch({status:"em curso",assignee:t.assignee||a.actor}); if(q("#treopen")) q("#treopen").onclick=()=>patch({status:"aberta"});
  if(q("#tdel")) q("#tdel").onclick=async()=>{ if(!confirm(T.delQ)) return; await fetch(API+"/tasks/"+t.id+"?actor="+encodeURIComponent(a.actor),{method:"DELETE",headers:hdr()}); await load(); list(); };
  if(q("#titem")) q("#titem").onclick=()=>{ if(t.lat!=null) map.setView([t.lat,t.lon],19); const id=t.feature_id; map.eachLayer(l=>{ if(l.feature&&l.__ed&&l.feature.properties.id===id) l.fire("click",{latlng:L.latLng(t.lat,t.lon)}); }); }; }
function newTask(pre){ const a=auth(); if(a.role==="viewer"){ toast&&toast(T.signin); return; } pre=pre||{}; const p=ensurePanel(); p.hidden=false;
  p.innerHTML=`<div class="hd"><h3>+ ${T.newT}</h3><button id="tclose">✕</button></div><div class="bd"><label>${T.title}<input id="tt" autofocus value="${esc(pre.title||"")}"></label><label>${T.detail}<textarea id="td"></textarea></label><div class="g2"><label>${T.who}<input id="ta" list="tpeople" value="${esc(pre.assignee||"")}"><datalist id="tpeople">${[...new Set(tasks.flatMap(t=>[t.assignee,t.created_by]).filter(Boolean))].map(n=>`<option value="${esc(n)}">`).join("")}</datalist></label><label>${T.due}<input id="tdu" type="date"></label></div><label>${T.prio}<select id="tp">${Object.entries(T.p).map(([k,v])=>`<option value="${k}" ${k==="normal"?"selected":""}>${v}</option>`).join("")}</select></label>
  <div style="font:12px var(--ui);color:var(--muted)" id="twhere">${pre.latlng?`📍 ${pre.latlng.lat.toFixed(5)}, ${pre.latlng.lng.toFixed(5)}${pre.feature_id?" · "+esc(pre.feature_id):""}`:T.here}</div></div>
  <div class="ft"><button id="tsave">${T.save}</button><button class="x" id="tcancel">${T.cancel}</button></div>`;
  p.querySelector("#tclose").onclick=close; p.querySelector("#tcancel").onclick=()=>{ map.off("click",pick); mapEl.classList.remove("ed-draw"); list(); };
  let ll=pre.latlng||null; const pick=e=>{ ll=e.latlng; p.querySelector("#twhere").textContent=`📍 ${ll.lat.toFixed(5)}, ${ll.lng.toFixed(5)}`; mapEl.classList.remove("ed-draw"); map.off("click",pick); };
  if(!ll){ mapEl.classList.add("ed-draw"); setTimeout(()=>map.on("click",pick),0); }
  p.querySelector("#tsave").onclick=async()=>{ const title=p.querySelector("#tt").value.trim(); if(!title){ p.querySelector("#tt").focus(); return; } map.off("click",pick); mapEl.classList.remove("ed-draw");
    const r=await fetch(API+"/tasks",{method:"POST",headers:hdr(),body:JSON.stringify({site:SITE_ID,title,detail:p.querySelector("#td").value.trim(),assignee:p.querySelector("#ta").value.trim(),due:p.querySelector("#tdu").value||null,priority:p.querySelector("#tp").value,lon:ll?ll.lng:null,lat:ll?ll.lat:null,feature_id:pre.feature_id||null,actor:a.actor})}).then(r=>r.json()).catch(()=>({}));
    if(r.ok){ toast&&toast(T.created); await load(); open(tasks.find(t=>t.id===r.id)); } else toast&&toast(r.error||"—"); }; }
window.edrTasks={list,newTask,open:(id)=>{ const t=tasks.find(x=>x.id===id); if(t) open(t); },reload:load};
// nav pill
(function mk(n){ const nav=document.getElementById("appnav"); const edit=document.getElementById("nav-edit"); if(!nav||!edit){ if((n||0)<40) setTimeout(()=>mk((n||0)+1),150); return; } if(document.getElementById("nav-tasks")) return; const b=document.createElement("button"); b.className="tasks"; b.id="nav-tasks"; b.innerHTML=`✔ <span class="t">${T.tasks.toUpperCase()}</span> <span class="n">0</span>`; b.onclick=()=>{ if(panel&&!panel.hidden) close(); else list(); }; edit.parentNode.insertBefore(b,edit); badge(); })();
load(); setInterval(load,60000);
if(/[#&]task=([^&]+)/.test(location.hash)){ const id=location.hash.match(/task=([^&]+)/)[1]; setTimeout(()=>{ const t=tasks.find(x=>x.id===id); if(t) open(t); },1500); }
})();
